name: Compile server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install bam
        run: 
            git clone https://github.com/teeworlds/bam
            cd bam
            git checkout v0.4.0
            ./make_unix.sh
            mv bam ../teeworlds-xPanic/

      - name: Compile binary server file
        run: ./bam server_release
