name: Compile server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: |
          sudo apt update
          sudo apt install git libfreetype6-dev libsdl2-dev libpnglite-dev libwavpack-dev python3 build-essential cmake -y
          cd /home/runner/work/teeworlds-xPanic/teeworlds-xPanic/
          git clone https://github.com/teeworlds/bam
          cd bam
          git checkout v0.4.0
          ./make_unix.sh
          mv bam ../
          ./bam server_release
